# Generated by Django 6.1.1 on 2026-09-09 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('todols', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100)),
                ('prenom', models.CharField(blank=True, max_length=100)),
                ('userid', models.CharField(max_length=100, unique=True)),
                ('mot_de_passe', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TacheProprietaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todols.tache')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mon_auth.user')),
            ],
            options={
                'unique_together': {('user', 'tache')},
            },
        ),
    ]
