# Generated by Django 6.1.1 on 2026-09-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'En cours'), ('DONE', 'Terminee')], default='PENDING', max_length=10)),
                ('priorite', models.CharField(choices=[('BASE', 'Base'), ('MOYENNE', 'Moyenne'), ('HAUTE', 'Haute')], default='MOYENNE', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_echeance', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
    ]
